#!/bin/bash
# Generate AWS Karuta audio files using Amazon Polly (Neural, Tomoko, slow rate)
# Upper phrase + 1s break + Bottom phrase

aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">バケット内のテキストを<break time="1s"/>自由にクエリ Amazon Athena</prosody></speak>' Amazon-Athena.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">モデルを選んで呼ぶだけで<break time="1s"/>AI が答える Amazon Bedrock</prosody></speak>' Amazon-Bedrock.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">桁違いの処理速度<break time="1s"/>量子コンピューティング アマゾン ブラケット</prosody></speak>' Amazon-Braket.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">世界のどこから繋いでも<break time="1s"/>快適アクセス Amazon CloudFront</prosody></speak>' Amazon-CloudFront.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ユーザープールもフェデレートも<break time="1s"/>認証するなら Amazon Cognito</prosody></speak>' Amazon-Cognito.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">交換機も電話機も<break time="1s"/>無くても通話 Amazon Connect</prosody></speak>' Amazon-Connect.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">蛇口にホースを繋ぐように<break time="1s"/>データが流れる Amazon Data Firehose</prosody></speak>' Amazon-Data-Firehose.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">Key と Value で入れていく<break time="1s"/>スキャンとクエリで アマゾン ダイナモ デービー</prosody></speak>' Amazon-DynamoDB.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">電源落ちても大丈夫<break time="1s"/>データは永続 Amazon EBS</prosody></speak>' Amazon-Elastic-Block-Store-\(EBS\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ハードのお世話は もうしない<break time="1s"/>欲しいときだけ アマゾン イーシーツー</prosody></speak>' Amazon-Elastic-Compute-Cloud-\(EC2\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">コンテナ管理で悩むなら<break time="1s"/>タスクに任せて Amazon ECS</prosody></speak>' Amazon-Elastic-Container-Service-\(ECS\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">複数インスタンスまたいでも<break time="1s"/>共有ストレージ アマゾン イーエフエス</prosody></speak>' Amazon-Elastic-File-System-\(EFS\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">マルチプレイのサーバーを<break time="1s"/>スケーリングお任せ Amazon GameLift</prosody></speak>' Amazon-GameLift.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">不審な行動、見つけ出す<break time="1s"/>脅威検知は アマゾン ガードデューティーで</prosody></speak>' Amazon-GuardDuty.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">脆弱性を見つけ出す<break time="1s"/>継続検査を Amazon Inspector で</prosody></speak>' Amazon-Inspector.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ライブ配信のインフラを<break time="1s"/>低遅延で届ける アマゾン アイブイエス</prosody></speak>' Amazon-Interactive-Video-Service-\(IVS\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">バケット覗いて見つけ出す<break time="1s"/>機密データ発見 Amazon Macie</prosody></speak>' Amazon-Macie.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">信頼できる台帳が欲しければ<break time="1s"/>改ざんさせない Amazon Managed Blockchain</prosody></speak>' Amazon-Managed-Blockchain.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ログも全文検索も<break time="1s"/>まとめて検索 Amazon OpenSearch</prosody></speak>' Amazon-OpenSearch-Service.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">書いた文章そのまんま<break time="1s"/>読み上げてくれる Amazon Polly</prosody></speak>' Amazon-Polly.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ビーアイツールだけじゃない<break time="1s"/>AI コンシェルジュ Amazon Quick</prosody></speak>' Amazon-Quick.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">高速、縦向き検索の<break time="1s"/>データウェアハウス Amazon Redshift</prosody></speak>' Amazon-Redshift.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">データベースの障害だ<break time="1s"/>フェイルオーバー Amazon RDS</prosody></speak>' Amazon-Relational-Database-Service-\(RDS\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">大量メール配信を<break time="1s"/>スケーラブルに アマゾン エスイーエス</prosody></speak>' Amazon-Simple-Email-Service-\(SES\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">Pub/Sub でファンアウト<break time="1s"/>通知を届ける Amazon SNS</prosody></speak>' Amazon-Simple-Notification-Service-\(SNS\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">メッセージを溜めて順番に<break time="1s"/>疎結合なら Amazon SQS</prosody></speak>' Amazon-Simple-Queue-Service-\(SQS\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">イレブンナインの耐久性<break time="1s"/>オブジェクトストレージ アマゾン エススリー</prosody></speak>' Amazon-Simple-Storage-Service-\(S3\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">紙の書類もスキャンして<break time="1s"/>文字を抽出 Amazon Textract</prosody></speak>' Amazon-Textract.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">クラウド、セキュアに隔離して<break time="1s"/>限定アクセス Amazon VPC</prosody></speak>' Amazon-Virtual-Private-Cloud-\(VPC\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">あちこち分散サービスを<break time="1s"/>ひとつにつなぐ AWS AppSync</prosody></speak>' AWS-AppSync.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">裏ではコンテナ動きます<break time="1s"/>バッチ処理なら AWS Batch</prosody></speak>' AWS-Batch.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">証明書の管理なら<break time="1s"/>お任せ Amazon Certificate Manager</prosody></speak>' AWS-Certificate-Manager-\(ACM\).mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ハードウェアで鍵管理<break time="1s"/>エーダブリューエス クラウドエイチエスエム</prosody></speak>' AWS-CloudHSM.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">やっぱりお前が必要だ<break time="1s"/>Git 管理は エーダブリューエス コードコミットで</prosody></speak>' AWS-CodeCommit.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">裏では VM 動きます<break time="1s"/>CI/CD エーダブリューエス コードデプロイ</prosody></speak>' AWS-CodeDeploy.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ログ調査の手が足りない<break time="1s"/>猫の手なります エーダブリューエス デブオプスエージェント</prosody></speak>' AWS-DevOps-Agent.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">専用線接続で<break time="1s"/>通信安定 AWS Direct Connect</prosody></speak>' AWS-Direct-Connect.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">異なるデータ形式を<break time="1s"/>ETL 処理 AWS Glue</prosody></speak>' AWS-Glue.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">サムル連携も SSO も<break time="1s"/>おまかせ エーダブリューエス アイアム アイデンティティセンター</prosody></speak>' AWS-IAM-Identity-Center.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">モノとクラウドをつなぐなら<break time="1s"/>デバイス通信 AWS IoT Core</prosody></speak>' AWS-IoT-Core.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">うまれてはや じゅういち年<break time="1s"/>サーバーレスサービス AWS Lambda</prosody></speak>' AWS-Lambda.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">AD サーバー買い換える<break time="1s"/>前に検討 AWS Managed Microsoft AD</prosody></speak>' AWS-Managed-Microsoft-AD.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">侵入テストも考えます<break time="1s"/>Continuum に統合された AWS Security Agent</prosody></speak>' AWS-Security-Agent-part-of-AWS-Continuum.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">コンプライアンス準拠なら<break time="1s"/>スコアで見える化 AWS Security Hub CSPM</prosody></speak>' AWS-Security-Hub-CSPM.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">OCSF 形式で<break time="1s"/>まとめて収集 AWS Security Lake</prosody></speak>' AWS-Security-Lake.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">ステートマシンを操って<break time="1s"/>柔軟に処理する AWS Step Functions</prosody></speak>' AWS-Step-Functions.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">サーバー管理はお任せを！<break time="1s"/>パッチも当てれる AWS Systems Manager</prosody></speak>' AWS-Systems-Manager.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">リフトアンドシフトなら<break time="1s"/>名前が変わった AWS Transform MGN</prosody></speak>' AWS-Transform-MGN.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">フルメッシュに疲れたら<break time="1s"/>アタッチメントで楽々 AWS Transit Gateway</prosody></speak>' AWS-Transit-Gateway.mp3
aws polly synthesize-speech --output-format mp3 --engine neural --voice-id Tomoko --region us-west-2 --text-type ssml --text '<speak><prosody rate="slow">わずか数分でブロックが<break time="1s"/>できるようになった AWS WAF</prosody></speak>' AWS-WAF.mp3
